sudo: false

language: php
php:
  - 5.6
  - 5.5
  - 5.4
  - 5.3

services: mongodb

before_script:
  - echo "extension = mongo.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - "mongo --eval 'db.adminCommand({ setParameter: true, textSearchEnabled : true}).ok === 1'"
  - composer update --no-interaction
  
script:
  - mongod --version
  - php -r "echo \MongoClient::VERSION . PHP_EOL;"
  - mkdir -p log
