sudo: false

dist: trusty

language: php

php:
  - nightly
  - 7.2
  - 7.1
  - 7.0
  - 5.6
  - 5.5
  - 5.4

matrix:
  allow_failures:
    - php: nightly
  include:
    - php: "5.3"
      dist: precise

addons:
  apt:
    sources:
      - mongodb-3.2-precise
    packages:
      - mongodb-org-server

services: mongodb

before_script:
  - PHP_VERSION=$(php -r 'echo phpversion();')
  - mongod --version
  - echo $TRAVIS_PHP_VERSION
  - echo $PHP_VERSION
  - if [[ ${PHP_VERSION:0:2} == "5." ]]; then echo "extension = mongo.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; fi
  - if [[ ${PHP_VERSION:0:2} == "5." ]]; then php -r "echo \MongoClient::VERSION . PHP_EOL;"; fi
  - if [[ ${PHP_VERSION:0:2} == "7." ]]; then echo "extension = mongodb.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; fi
  - if [[ ${PHP_VERSION:0:2} == "7." ]]; then php -r 'echo MONGODB_VERSION . PHP_EOL;'; fi
  - composer update --no-interaction
  - if [[ ${PHP_VERSION:0:2} == "7." ]]; then composer require "alcaeus/mongo-php-adapter"; fi

script:
  - echo "Currently not implemented"
